# Generated by ys-bench scripts/release-macos.zsh -- do not edit by hand.
# Built from ys-bench ade9f1b-dirty, Developer ID signed and notarized, and
# published to the Forgejo generic package registry (anonymously readable).
#
# This is a BINARY formula: one universal (arm64 + x86_64) Mach-O.
class YsearchDemo < Formula
  desc "Query the public YoloSearch FineWeb benchmark corpus from your terminal"
  homepage "https://yolosearch.teixos.net"
  url "https://git.teixos.net/api/packages/yannick/generic/ysearch-demo/ade9f1b-dirty/ysearch-demo-ade9f1b-dirty-macos-universal.tar.gz"
  version "ade9f1b-dirty"
  sha256 "6707908a7619ca168e7d8948d41fc8e9d4b3d37e71667b397d3b87a25186e367"

  depends_on :macos

  def install
    bin.install "ysearch-demo"
  end

  def caveats
    # Single-quoted heredoc: Ruby must not read \f as a form feed.
    <<~'EOS'
      ysearch-demo is a client: it holds no search engine. It queries the
      yolosearch-demo container, which needs Apple's container runtime:

        brew install --cask container

      Then just run it. It offers to start the container the first time:

        ysearch-demo

      The corpus is public and read-only, so nothing needs credentials. The
      container caches corpus metadata in ~/.ysearch (about 110 MB), which is
      what makes the second start fast. Deleting it is safe.

        ysearch-demo                    open the query REPL
        ysearch-demo 'text:kubernetes'  run one query
        ysearch-demo serverlog -f       follow the container's output

      In the REPL, \fields lists every field the corpus holds.
    EOS
  end

  test do
    # Runs without a server, which is what a bottle test can check: it catches
    # a broken or wrongly-signed build. Querying would need the container.
    assert_match "ysearch-demo", shell_output("#{bin}/ysearch-demo version")
  end
end
