# Generated by ys-bench scripts/release-macos.zsh -- do not edit by hand.
# Built from ys-bench v0.4.4 (fd40ddb), Developer ID signed and notarized, and
# published to the Forgejo generic package registry (anonymously readable).
#
# This is a BINARY formula: one universal (arm64 + x86_64) Mach-O.
class YsearchDemo < Formula
  desc "Query the public YoloSearch FineWeb benchmark corpus from your terminal"
  homepage "https://yolosearch.teixos.net"
  url "https://git.teixos.net/api/packages/yannick/generic/ysearch-demo-release/v0.4.4/ysearch-demo-v0.4.4-macos-universal.tar.gz"
  version "0.4.4"
  sha256 "7d1a0ea1e99154423809735fd6394d4f25665002ea649da6c9e1f7a16e204d25"

  depends_on :macos

  # Apple's container runtime serves the demo corpora. It runs only on Apple
  # silicon with macOS 26 or newer, so it is required there and nowhere else:
  # on an Intel Mac or an older macOS, ysearch-demo still installs and queries
  # a server you name with --address.
  on_macos do
    on_arm do
      on_tahoe :or_newer do
        depends_on "container"
      end
    end
  end

  def install
    bin.install "ysearch-demo"
  end

  def caveats
    # Single-quoted heredoc: Ruby must not read \f as a form feed.
    <<~'EOS'
      ysearch-demo is a client: it holds no search engine. It queries the
      yolosearch-demo container, which runs on Apple's container runtime.
      On an Apple silicon Mac with macOS 26 or newer, Homebrew installed the
      runtime along with ysearch-demo. Start it once:

        container system start

      Then just run it. It offers to start the container the first time:

        ysearch-demo

      The corpus is public and read-only, so nothing needs credentials. The
      container caches corpus metadata in ~/.ysearch (about 110 MB), which is
      what makes the second start fast. Deleting it is safe.

        ysearch-demo                    open the query REPL
        ysearch-demo 'text:kubernetes'  run one query
        ysearch-demo serverlog -f       follow the container's output
        ysearch-demo zap                delete the container and its cache

      In the REPL, \fields lists every field the corpus holds.
    EOS
  end

  test do
    # Runs without a server, which is what a bottle test can check: it catches
    # a broken or wrongly-signed build. Querying would need the container.
    assert_match "ysearch-demo", shell_output("#{bin}/ysearch-demo version")
  end
end
